/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceModel } from './ServiceModel';
import {
    ServiceModelFromJSON,
    ServiceModelFromJSONTyped,
    ServiceModelToJSON,
} from './ServiceModel';
import type { MooringTypeModel } from './MooringTypeModel';
import {
    MooringTypeModelFromJSON,
    MooringTypeModelFromJSONTyped,
    MooringTypeModelToJSON,
} from './MooringTypeModel';

/**
 * 
 * @export
 * @interface MooringModel
 */
export interface MooringModel {
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof MooringModel
     */
    geoJsonId?: number;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    coordinates?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    canalplanLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    canalName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MooringModel
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MooringModel
     */
    distance?: number | null;
    /**
     * 
     * @type {MooringTypeModel}
     * @memberof MooringModel
     */
    mooringType?: MooringTypeModel;
    /**
     * 
     * @type {Array<ServiceModel>}
     * @memberof MooringModel
     */
    services?: Array<ServiceModel> | null;
}

/**
 * Check if a given object implements the MooringModel interface.
 */
export function instanceOfMooringModel(value: object): value is MooringModel {
    return true;
}

export function MooringModelFromJSON(json: any): MooringModel {
    return MooringModelFromJSONTyped(json, false);
}

export function MooringModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MooringModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'geoJsonId': json['geoJsonId'] == null ? undefined : json['geoJsonId'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
        'canalplanLink': json['canalplanLink'] == null ? undefined : json['canalplanLink'],
        'website': json['website'] == null ? undefined : json['website'],
        'address': json['address'] == null ? undefined : json['address'],
        'canalName': json['canalName'] == null ? undefined : json['canalName'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'mooringType': json['mooringType'] == null ? undefined : MooringTypeModelFromJSON(json['mooringType']),
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(ServiceModelFromJSON)),
    };
}

export function MooringModelToJSON(value?: MooringModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'geoJsonId': value['geoJsonId'],
        'name': value['name'],
        'type': value['type'],
        'coordinates': value['coordinates'],
        'canalplanLink': value['canalplanLink'],
        'website': value['website'],
        'address': value['address'],
        'canalName': value['canalName'],
        'notes': value['notes'],
        'phoneNumber': value['phoneNumber'],
        'distance': value['distance'],
        'mooringType': MooringTypeModelToJSON(value['mooringType']),
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(ServiceModelToJSON)),
    };
}

