/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewMarinaSuggestionModel
 */
export interface NewMarinaSuggestionModel {
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    readonly sessionId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NewMarinaSuggestionModel
     */
    readonly requestTimestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    marinaName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    websiteLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    canalName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewMarinaSuggestionModel
     */
    services?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof NewMarinaSuggestionModel
     */
    otherComments?: string | null;
}

/**
 * Check if a given object implements the NewMarinaSuggestionModel interface.
 */
export function instanceOfNewMarinaSuggestionModel(value: object): value is NewMarinaSuggestionModel {
    return true;
}

export function NewMarinaSuggestionModelFromJSON(json: any): NewMarinaSuggestionModel {
    return NewMarinaSuggestionModelFromJSONTyped(json, false);
}

export function NewMarinaSuggestionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewMarinaSuggestionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'requestTimestamp': json['requestTimestamp'] == null ? undefined : (new Date(json['requestTimestamp'])),
        'marinaName': json['marinaName'] == null ? undefined : json['marinaName'],
        'websiteLink': json['websiteLink'] == null ? undefined : json['websiteLink'],
        'address': json['address'] == null ? undefined : json['address'],
        'canalName': json['canalName'] == null ? undefined : json['canalName'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'services': json['services'] == null ? undefined : json['services'],
        'otherComments': json['otherComments'] == null ? undefined : json['otherComments'],
    };
}

export function NewMarinaSuggestionModelToJSON(value?: Omit<NewMarinaSuggestionModel, 'id'|'sessionId'|'requestTimestamp'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'marinaName': value['marinaName'],
        'websiteLink': value['websiteLink'],
        'address': value['address'],
        'canalName': value['canalName'],
        'phoneNumber': value['phoneNumber'],
        'services': value['services'],
        'otherComments': value['otherComments'],
    };
}

