/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMarinaSuggestionModel
 */
export interface UpdateMarinaSuggestionModel {
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    marinaId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    readonly sessionId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateMarinaSuggestionModel
     */
    readonly requestTimestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    userEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    suggestedName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    suggestedCoordinates?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    suggestedWebsite?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    suggestedAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    suggestedCanalName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    suggestedPhoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMarinaSuggestionModel
     */
    otherComments?: string | null;
}

/**
 * Check if a given object implements the UpdateMarinaSuggestionModel interface.
 */
export function instanceOfUpdateMarinaSuggestionModel(value: object): value is UpdateMarinaSuggestionModel {
    return true;
}

export function UpdateMarinaSuggestionModelFromJSON(json: any): UpdateMarinaSuggestionModel {
    return UpdateMarinaSuggestionModelFromJSONTyped(json, false);
}

export function UpdateMarinaSuggestionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMarinaSuggestionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'marinaId': json['marinaId'] == null ? undefined : json['marinaId'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'requestTimestamp': json['requestTimestamp'] == null ? undefined : (new Date(json['requestTimestamp'])),
        'userEmail': json['userEmail'] == null ? undefined : json['userEmail'],
        'suggestedName': json['suggestedName'] == null ? undefined : json['suggestedName'],
        'suggestedCoordinates': json['suggestedCoordinates'] == null ? undefined : json['suggestedCoordinates'],
        'suggestedWebsite': json['suggestedWebsite'] == null ? undefined : json['suggestedWebsite'],
        'suggestedAddress': json['suggestedAddress'] == null ? undefined : json['suggestedAddress'],
        'suggestedCanalName': json['suggestedCanalName'] == null ? undefined : json['suggestedCanalName'],
        'suggestedPhoneNumber': json['suggestedPhoneNumber'] == null ? undefined : json['suggestedPhoneNumber'],
        'otherComments': json['otherComments'] == null ? undefined : json['otherComments'],
    };
}

export function UpdateMarinaSuggestionModelToJSON(value?: Omit<UpdateMarinaSuggestionModel, 'id'|'sessionId'|'requestTimestamp'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'marinaId': value['marinaId'],
        'userEmail': value['userEmail'],
        'suggestedName': value['suggestedName'],
        'suggestedCoordinates': value['suggestedCoordinates'],
        'suggestedWebsite': value['suggestedWebsite'],
        'suggestedAddress': value['suggestedAddress'],
        'suggestedCanalName': value['suggestedCanalName'],
        'suggestedPhoneNumber': value['suggestedPhoneNumber'],
        'otherComments': value['otherComments'],
    };
}

